find_path(SuiteSparse_INCLUDE_DIR NAMES SuiteSparse_config.h PATHS ${CONAN_INCLUDE_DIRS_SUITESPARSE})
#find_library(SuiteSparse_LIBRARY NAMES ${CONAN_LIBS_SUITESPARSE} PATHS ${CONAN_LIB_DIRS_SUITESPARSE})
#set(CONAN_LIBS_SUITESPARSE amd btf camd ccolamd colamdcholmod cxsparse klu spqr suitesparseconfig umfpack)
FOREACH(LIB ${CONAN_LIBS_SUITESPARSE})
        SET(FOUND_LIB "FOUND_LIB-NOTFOUND")
        FIND_LIBRARY(FOUND_LIB NAMES ${LIB} PATHS ${CONAN_LIB_DIRS_SUITESPARSE})
        if(SuiteSparse_LIBRARY)
            SET(SuiteSparse_LIBRARY "${SuiteSparse_LIBRARY} ${FOUND_LIB}")
        else()
            SET(SuiteSparse_LIBRARY "${FOUND_LIB}")
        endif()
ENDFOREACH(LIB)
set(SuiteSparse_FOUND TRUE)
set(SuiteSparse_INCLUDE_DIRS ${SuiteSparse_INCLUDE_DIR})
set(SuiteSparse_LIBRARIES ${SuiteSparse_LIBRARY})
mark_as_advanced(SuiteSparse_LIBRARY SuiteSparse_INCLUDE_DIR)